FROM golang:1.22-alpine

WORKDIR /app

# Install Air for hot-reloading during development
RUN go install github.com/air-verse/air@latest

COPY backend/go.mod backend/go.sum ./
RUN go mod download

COPY backend .

# Hot reload for development
CMD ["air", "-c", ".air.toml"]